"""DataGuardian API.  Run from the project root:  uvicorn backend.app:app --reload"""
import io
import json
import os
import uuid
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import Response
from fastapi.staticfiles import StaticFiles
from openai import OpenAI
from pydantic import BaseModel

from .engine import build_quality_report
from .prompts import SYSTEM_PROMPT_V1

ROOT = Path(__file__).resolve().parents[1]
MAX_BYTES, MAX_SESSIONS, MAX_HISTORY = 5 * 1024 * 1024, 200, 20

# Load .env (or _env) from the project root, notebooks/ or the working directory
for _dir in (ROOT, ROOT / "notebooks", Path.cwd()):
    _f = next((_dir / n for n in (".env", "_env") if (_dir / n).is_file()), None)
    if _f:
        load_dotenv(_f, override=True)
        break

API_KEY = os.getenv("GROQ_API_KEY")
BASE_URL = os.getenv("BASE_URL_GROQ")
MODEL = os.getenv("MODEL_NAME") or os.getenv("GROQ_MODEL")
client = OpenAI(api_key=API_KEY, base_url=BASE_URL) if (API_KEY and BASE_URL and MODEL) else None

app = FastAPI(title="DataGuardian")
sessions: dict = {}  # session_id -> {"filename", "report", "history"}


class ChatIn(BaseModel):
    session_id: str
    message: str


class SessionIn(BaseModel):
    session_id: str


def new_session(df: pd.DataFrame, filename: str) -> dict:
    report = build_quality_report(df)
    sid = uuid.uuid4().hex
    if len(sessions) >= MAX_SESSIONS:
        sessions.pop(next(iter(sessions)))
    sessions[sid] = {"filename": filename, "report": report, "history": []}
    return {"session_id": sid, "filename": filename, "report": report}


def get_session(sid: str) -> dict:
    if sid not in sessions:
        raise HTTPException(404, "Session expired. Please upload your CSV again.")
    return sessions[sid]


@app.get("/api/health")
def health():
    return {"ok": True, "llm_ready": client is not None, "model": MODEL}


@app.post("/api/upload")
async def upload(file: UploadFile = File(...)):
    if not (file.filename or "").lower().endswith(".csv"):
        raise HTTPException(400, "Please upload a .csv file.")
    raw = await file.read()
    if len(raw) > MAX_BYTES:
        raise HTTPException(413, "File too large (max 5 MB).")
    df = None
    for enc in ("utf-8-sig", "latin-1"):
        try:
            df = pd.read_csv(io.BytesIO(raw), encoding=enc)
            break
        except Exception:
            continue
    if df is None or df.empty or df.shape[1] == 0:
        raise HTTPException(400, "Could not read this CSV, or it is empty.")
    return new_session(df, file.filename)


@app.post("/api/sample")
def sample():
    path = ROOT / "data" / "sample_dataset.csv"
    if not path.exists():
        raise HTTPException(404, "data/sample_dataset.csv not found.")
    return new_session(pd.read_csv(path), "sample_dataset.csv")


@app.get("/api/report/{sid}")
def report(sid: str):
    s = get_session(sid)
    return Response(json.dumps(s["report"], indent=2, ensure_ascii=False), media_type="application/json",
                    headers={"Content-Disposition": 'attachment; filename="quality_report.json"'})


@app.post("/api/chat")
def chat(body: ChatIn):
    s = get_session(body.session_id)
    message = body.message.strip()[:2000]
    if not message:
        raise HTTPException(400, "Message cannot be empty.")
    if client is None:
        raise HTTPException(503, "LLM not configured. Add GROQ_API_KEY, BASE_URL_GROQ and MODEL_NAME to .env and restart.")
    context = ("DATA QUALITY REPORT\n===================\nGenerated by the Python Data Quality Engine. "
               "Treat these values as factual evidence.\n\n" + json.dumps(s["report"], indent=2, ensure_ascii=False))
    messages = [{"role": "system", "content": SYSTEM_PROMPT_V1},
                {"role": "system", "content": context},
                *s["history"][-MAX_HISTORY:],
                {"role": "user", "content": message}]
    try:
        r = client.chat.completions.create(model=MODEL, messages=messages, temperature=0.2)
        answer = (r.choices[0].message.content or "").strip() or "I was unable to generate an answer."
    except Exception as e:
        raise HTTPException(502, f"The language model could not be reached: {e}")
    s["history"] += [{"role": "user", "content": message}, {"role": "assistant", "content": answer}]
    return {"answer": answer}


@app.post("/api/reset")
def reset(body: SessionIn):
    get_session(body.session_id)["history"].clear()
    return {"ok": True}


app.mount("/", StaticFiles(directory=ROOT / "frontend", html=True), name="frontend")
